import ApplicantProfilePage from '@/components/templates/ApplicantProfileTemplate'
import React from 'react'
import { Application } from '@/constant/type';

const APPS: Application[] = [
  {
    id: "app-1",
    jobId: "job-1",
    jobTitle: "Senior Frontend Developer",
    candidateName: "Sarah Johnson",
    candidateEmail: "sarah.johnson@email.com",
    candidatePhone: "+1 (555) 123-4567",
    appliedDate: "2025-01-20",
    status: "shortlisted",
    experience: "5 years",
    location: "San Francisco, CA",
    resumeUrl: "/resume-sarah.pdf",
    coverLetter:
      "Excited to apply for the Senior Frontend Developer role. Strong in React, TypeScript, accessibility and performance.",
    rating: 4.5,
    skills: ["React", "TypeScript", "GraphQL", "Jest", "Next.js", "Tailwind CSS"],
    education: "BS Computer Science, Stanford University",
    currentCompany: "Tech Solutions Inc.",
    noticePeriod: "2 weeks",
    expectedSalary: "$140,000 - $160,000",
    linkedIn: "https://linkedin.com/in/sarahjohnson",
    portfolio: "https://sarahjohnson.dev",
    languages: ["English", "Spanish"],
    certifications: ["AWS Certified Developer", "Google Cloud Professional"],
  },
  {
    id: "app-2",
    jobId: "job-1",
    jobTitle: "Senior Frontend Developer",
    candidateName: "Michael Chen",
    candidateEmail: "michael.chen@email.com",
    candidatePhone: "+1 (555) 987-6543",
    appliedDate: "2025-01-18",
    status: "reviewed",
    experience: "7 years",
    location: "Oakland, CA",
    resumeUrl: "/resume-michael.pdf",
    coverLetter:
      "Led multiple frontend teams delivering scalable apps. Strong in React, testing, and architecture.",
    rating: 4.2,
    skills: ["React", "Node.js", "AWS", "Docker", "Kubernetes"],
    education: "MS Software Engineering, UC Berkeley",
    currentCompany: "Digital Innovations Co.",
    noticePeriod: "1 month",
    expectedSalary: "$150,000 - $170,000",
    linkedIn: "https://linkedin.com/in/michaelchen",
    languages: ["English", "Mandarin"],
    certifications: ["PMP", "Certified Scrum Master"],
  },
  {
    id: "app-3",
    jobId: "job-1",
    jobTitle: "Senior Frontend Developer",
    candidateName: "David Kim",
    candidateEmail: "david.kim@email.com",
    candidatePhone: "+1 (555) 321-9876",
    appliedDate: "2025-01-14",
    status: "pending",
    experience: "4 years",
    location: "San Jose, CA",
    resumeUrl: "/resume-david.pdf",
    coverLetter:
      "Passionate about clean code and UX. Built responsive apps and optimized performance.",
    skills: ["JavaScript", "React", "CSS", "Redux"],
    education: "BS Computer Science, UC Davis",
    currentCompany: "WebDev Studios",
    noticePeriod: "2 weeks",
    expectedSalary: "$120,000 - $140,000",
    linkedIn: "https://linkedin.com/in/davidkim",
    portfolio: "https://davidkim.com",
    languages: ["English", "Korean"],
  },

  // job-2 Product Manager (2)
  {
    id: "app-4",
    jobId: "job-2",
    jobTitle: "Product Manager",
    candidateName: "Emily Rodriguez",
    candidateEmail: "emily.rodriguez@email.com",
    candidatePhone: "+1 (555) 456-7890",
    appliedDate: "2025-01-16",
    status: "interviewed",
    experience: "6 years",
    location: "New York, NY",
    resumeUrl: "/resume-emily.pdf",
    coverLetter:
      "Seasoned PM with track record launching data-informed products and leading cross-functional teams.",
    rating: 4.8,
    skills: ["Product Strategy", "Agile", "User Research", "Analytics", "Roadmap Planning"],
    education: "MBA, Columbia Business School",
    currentCompany: "StartupXYZ",
    noticePeriod: "3 weeks",
    expectedSalary: "$145,000 - $165,000",
    linkedIn: "https://linkedin.com/in/emilyrodriguez",
    languages: ["English", "French"],
    certifications: ["Product Management Certificate", "Lean Six Sigma Green Belt"],
  },
  {
    id: "app-5",
    jobId: "job-2",
    jobTitle: "Product Manager",
    candidateName: "Ravi Patel",
    candidateEmail: "ravi.patel@email.com",
    candidatePhone: "+1 (555) 222-3344",
    appliedDate: "2025-01-19",
    status: "pending",
    experience: "5 years",
    location: "Jersey City, NJ",
    resumeUrl: "/resume-ravi.pdf",
    coverLetter:
      "PM with B2B SaaS experience, strong analytics background and customer discovery practice.",
    skills: ["JIRA", "SQL", "Experimentation", "Stakeholder Management"],
    education: "BS Information Systems, Rutgers University",
    expectedSalary: "$135,000 - $155,000",
    linkedIn: "https://linkedin.com/in/ravipatel",
  },

  // job-3 UX Designer (2)
  {
    id: "app-6",
    jobId: "job-3",
    jobTitle: "UX Designer",
    candidateName: "Hannah Lee",
    candidateEmail: "hannah.lee@email.com",
    candidatePhone: "+1 (555) 111-2233",
    appliedDate: "2025-01-12",
    status: "reviewed",
    experience: "4 years",
    location: "Los Angeles, CA",
    resumeUrl: "/resume-hannah.pdf",
    coverLetter:
      "UX designer focused on accessible design, prototyping, and usability testing.",
    rating: 4.3,
    skills: ["Figma", "Prototyping", "Usability Testing", "Design Systems"],
    education: "BA Interaction Design, UCLA",
    portfolio: "https://hannahlee.design",
  },
  {
    id: "app-7",
    jobId: "job-3",
    jobTitle: "UX Designer",
    candidateName: "Omar Farouk",
    candidateEmail: "omar.farouk@email.com",
    candidatePhone: "+1 (555) 998-7766",
    appliedDate: "2025-01-09",
    status: "pending",
    experience: "3 years",
    location: "Pasadena, CA",
    resumeUrl: "/resume-omar.pdf",
    coverLetter:
      "I love solving user problems with simple, elegant flows. Comfortable with design handoff.",
    skills: ["Wireframing", "Figma", "HTML/CSS"],
    education: "BS Human-Computer Interaction, UC San Diego",
  },

  // job-4 Data Scientist (3)
  {
    id: "app-8",
    jobId: "job-4",
    jobTitle: "Data Scientist",
    candidateName: "Ling Wu",
    candidateEmail: "ling.wu@email.com",
    candidatePhone: "+1 (555) 444-7788",
    appliedDate: "2025-01-18",
    status: "shortlisted",
    experience: "6 years",
    location: "Seattle, WA",
    resumeUrl: "/resume-ling.pdf",
    coverLetter:
      "Data scientist specializing in ML for user growth and personalization.",
    rating: 4.7,
    skills: ["Python", "TensorFlow", "PyTorch", "SQL", "Airflow"],
    education: "MS Data Science, University of Washington",
    currentCompany: "NorthStar Analytics",
  },
  {
    id: "app-9",
    jobId: "job-4",
    jobTitle: "Data Scientist",
    candidateName: "Mateo Silva",
    candidateEmail: "mateo.silva@email.com",
    candidatePhone: "+1 (555) 555-1212",
    appliedDate: "2025-01-17",
    status: "reviewed",
    experience: "4 years",
    location: "Bellevue, WA",
    resumeUrl: "/resume-mateo.pdf",
    coverLetter:
      "Built forecasting pipelines and experimentation frameworks at scale.",
    skills: ["R", "Python", "Forecasting", "Experiment Design"],
    education: "BS Statistics, UW",
  },
  {
    id: "app-10",
    jobId: "job-4",
    jobTitle: "Data Scientist",
    candidateName: "Nora Ahmed",
    candidateEmail: "n.ahmed@email.com",
    candidatePhone: "+1 (555) 909-4545",
    appliedDate: "2025-01-22",
    status: "pending",
    experience: "3 years",
    location: "Seattle, WA",
    resumeUrl: "/resume-nora.pdf",
    coverLetter:
      "Keen on causal inference and uplift modeling. Looking to grow in a product DS role.",
    skills: ["Python", "SQL", "Causal Inference", "Tableau"],
    education: "MS Applied Math, UW",
  },

  // job-5 DevOps Engineer (2)
  {
    id: "app-11",
    jobId: "job-5",
    jobTitle: "DevOps Engineer",
    candidateName: "Jonas Müller",
    candidateEmail: "jonas.mueller@email.com",
    candidatePhone: "+1 (555) 232-7788",
    appliedDate: "2025-01-11",
    status: "interviewed",
    experience: "8 years",
    location: "Austin, TX",
    resumeUrl: "/resume-jonas.pdf",
    coverLetter:
      "Infra as Code evangelist. Built CI/CD for microservices on EKS and GKE.",
    rating: 4.6,
    skills: ["AWS", "Terraform", "Kubernetes", "GitHub Actions", "Prometheus"],
    education: "BS Computer Engineering, UT Austin",
  },
  {
    id: "app-12",
    jobId: "job-5",
    jobTitle: "DevOps Engineer",
    candidateName: "Priya Nair",
    candidateEmail: "priya.nair@email.com",
    candidatePhone: "+1 (555) 667-2211",
    appliedDate: "2025-01-15",
    status: "pending",
    experience: "5 years",
    location: "Dallas, TX",
    resumeUrl: "/resume-priya.pdf",
    coverLetter:
      "Focused on observability, incident response and cost optimization.",
    skills: ["Azure", "Pulumi", "Helm", "Grafana", "ArgoCD"],
    education: "BS Information Technology, UT Dallas",
  },

  // job-6 Marketing Specialist (2)
  {
    id: "app-13",
    jobId: "job-6",
    jobTitle: "Marketing Specialist",
    candidateName: "Olivia Brown",
    candidateEmail: "olivia.brown@email.com",
    candidatePhone: "+1 (555) 765-2234",
    appliedDate: "2024-12-28",
    status: "rejected",
    experience: "3 years",
    location: "Chicago, IL",
    resumeUrl: "/resume-olivia.pdf",
    coverLetter:
      "Content and lifecycle marketer with strong email and CRM chops.",
    skills: ["HubSpot", "SEO", "Copywriting", "A/B Testing"],
    education: "BA Marketing, DePaul University",
  },
  {
    id: "app-14",
    jobId: "job-6",
    jobTitle: "Marketing Specialist",
    candidateName: "Noah Wilson",
    candidateEmail: "noah.wilson@email.com",
    candidatePhone: "+1 (555) 876-1122",
    appliedDate: "2025-01-02",
    status: "hired",
    experience: "4 years",
    location: "Chicago, IL",
    resumeUrl: "/resume-noah.pdf",
    coverLetter:
      "Owned paid + organic funnels. Comfortable with attribution and dashboards.",
    rating: 4.4,
    skills: ["Google Ads", "Meta Ads", "Analytics", "Looker Studio"],
    education: "BS Business, University of Illinois",
  },
]; 

const ApplicantDetails = () => {
  return (
    <ApplicantProfilePage application={APPS[1]}/>
  )
}

export default ApplicantDetails